
security:
  jwt:
    # Provide via environment: export JWT_SECRET='a-64-plus-character-random-string'
    secret: ${JWT_SECRET:saiofal;vkasfbehwqpofhjashofjaswfpojasfvbafop[hfifonfo[shjfwefjjfslajfsahfoshffasnbash[f}
    issuer: ${JWT_ISSUER:auth-backend}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:900}       # 15 minutes
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:1209600} # 14 days
    refresh-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refresh_token}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:Lax}
spring:
  application:
    name: auth-backend


  #database configuration
  datasource:
    # Neon JDBC URL (copied from your psql string, but with jdbc: prefix)
    url: jdbc:mysql://mysql-47ed078-vijaymcse2024-60f1.h.aivencloud.com:20527/defaultdb
    username: avnadmin
    password: AVNS_CFR4vOCSabBxa2TJw4R

    hikari:
      pool-name: neon-hikari
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000        # 30s
      connection-timeout: 20000  # 20s
      max-lifetime: 1800000      # 30m (keep below Neonâ€™s TCP idle timeouts)
      validation-timeout: 5000
      leak-detection-threshold: 0
      initialization-fail-timeout: -1  # don't fail app if DB is momentarily unavailable

  jpa:
    hibernate:
      ddl-auto: update            # dev only; use Flyway in prod
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect


  security:
    #oauth2 configuration
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
              - openid
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id


app:
  cors:
    allowed-origins: "http://localhost:5173"
  auth:
    success-redirect: "http://localhost:5173/auth/success"
    failure-redirect: "http://localhost:5173/auth/failure"


logging.level.com.substring.auth.app: DEBUG
